# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Build ROCK

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        system:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.system.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup LXD
        uses: canonical/setup-lxd@da2ac84e727dc534215fd14cd088b9209d65893b # main
        with:
          channel: 6/stable

      - name: Install tooling
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic
          sudo snap install regclient --classic
          sudo snap install just --classic

      - name: Build rock
        id: build
        run: |
          rockcraft pack --verbose

      - name: Add additional labels and export to tar
        id: refine
        run: |
          just refine
          echo "tar=$(just get-tar-file)" >> $GITHUB_OUTPUT

      - name: Upload locally built artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: polaris-console-${{ matrix.system.arch }}
          path: ${{ steps.refine.outputs.tar }}
