# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: CI pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint rockcraft.yaml
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install tox
        run: sudo apt install just shfmt yamllint

      - name: Lint
        run: just lint

  build-rock:
    name: Build Rock (amd64 and arm64)
    needs: [lint]
    uses: ./.github/workflows/build.yaml

  integration:
    name: Run tests
    needs: [build-rock]
    uses: ./.github/workflows/integration.yaml

  trivy:
    name: CVE Scanning
    needs: [build-rock]
    uses: ./.github/workflows/trivy.yaml
    permissions:
      contents: read
      security-events: write
